spring:
  application:
    name: Curo
    description: ""
    version: 1

curo:
  print-stacktrace: false

camunda:
  bpm:
    admin-user:
      email: demo@demo.com
      first-name: demo
      last-name: demo
      password: demo
      id: demo
    default-serialization-format: application/json
    filter:
      create: ğŸŒ All tasks
